---
version: 6
users:
  AliakseiT:
    full_name: Aliaksei Tsitovich
    job_title: Management Representative
  InaTsitovich:
    full_name: Ina Tsitovich
    job_title: Quality Assurance Lead

roles:
  qa_lead:
    users:
      - InaTsitovich
    required_sops:
      - SOP-001
      - SOP-002
      - SOP-003
      - SOP-004
      - SOP-005
      - SOP-006
      - SOP-009
      - SOP-010
      - SOP-011
      - SOP-012
      - SOP-013
      - SOP-014
      - SOP-015
      - SOP-016
      - SOP-017
      - SOP-018
      - SOP-019
      - SOP-020
    required_revisions:
      SOP-001: R07
      SOP-002: R02
      SOP-003: R03
      SOP-004: R04
      SOP-005: R09
      SOP-009: R03
      SOP-010: R01
      SOP-011: R04
      SOP-012: R02
      SOP-013: R02
      SOP-014: R02
      SOP-016: R02
      SOP-017: R02
      SOP-018: R02
      SOP-019: R03
      SOP-020: R02

  engineer:
    users:
      - AliakseiT
      - InaTsitovich
    required_sops:
      - SOP-001
      - SOP-002
      - SOP-006
      - SOP-008
      - SOP-009
      - SOP-011
      - SOP-015
      - SOP-017
      - SOP-018
      - SOP-020
    required_revisions:
      SOP-001: R07
      SOP-002: R02
      SOP-008: R03
      SOP-009: R03
      SOP-011: R04
      SOP-017: R02
      SOP-018: R02
      SOP-020: R02

  engineering_lead:
    users:
      - AliakseiT
    required_sops:
      - SOP-001
      - SOP-002
      - SOP-006
      - SOP-007
      - SOP-008
      - SOP-009
      - SOP-011
      - SOP-015
      - SOP-017
      - SOP-018
      - SOP-019
      - SOP-020
    required_revisions:
      SOP-001: R07
      SOP-002: R02
      SOP-007: R03
      SOP-008: R03
      SOP-009: R03
      SOP-011: R04
      SOP-017: R02
      SOP-018: R02
      SOP-019: R03
      SOP-020: R02

  technical_qms_maintainer:
    users:
      - AliakseiT
    required_sops:
      - SOP-001
      - SOP-002
      - SOP-006
      - SOP-007
      - SOP-008
      - SOP-009
      - SOP-015
      - SOP-017
      - SOP-018
      - SOP-020
    required_revisions:
      SOP-001: R07
      SOP-002: R02
      SOP-006: R01
      SOP-007: R03
      SOP-008: R03
      SOP-009: R03
      SOP-017: R02
      SOP-018: R02
      SOP-020: R02

  regulatory_lead:
    users:
      - AliakseiT
    required_sops:
      - SOP-001
      - SOP-004
      - SOP-005
      - SOP-007
      - SOP-011
      - SOP-012
      - SOP-013
      - SOP-014
      - SOP-015
      - SOP-018
      - SOP-019
      - SOP-020
    required_revisions:
      SOP-001: R07
      SOP-004: R04
      SOP-005: R09
      SOP-007: R03
      SOP-011: R04
      SOP-012: R02
      SOP-013: R02
      SOP-014: R02
      SOP-018: R02
      SOP-019: R03
      SOP-020: R02

  auditor:
    users: []
    required_sops:
      - SOP-001
      - SOP-003
      - SOP-005
      - SOP-006
      - SOP-009
      - SOP-010
      - SOP-011
      - SOP-012
      - SOP-013
      - SOP-014
      - SOP-015
      - SOP-016
      - SOP-017
      - SOP-018
      - SOP-019
      - SOP-020
    required_revisions:
      SOP-001: R07
      SOP-003: R03
      SOP-005: R09
      SOP-010: R01
      SOP-011: R04
      SOP-012: R02
      SOP-013: R02
      SOP-014: R02
      SOP-017: R02
      SOP-016: R02
      SOP-018: R02
      SOP-019: R03
      SOP-020: R02

  management_representative:
    users:
      - AliakseiT
    required_sops:
      - SOP-001
      - SOP-002
      - SOP-004
      - SOP-005
      - SOP-007
      - SOP-009
      - SOP-010
      - SOP-011
      - SOP-013
      - SOP-016
      - SOP-017
      - SOP-018
      - SOP-019
      - SOP-020
    required_revisions:
      SOP-001: R07
      SOP-002: R02
      SOP-004: R04
      SOP-005: R09
      SOP-007: R03
      SOP-009: R03
      SOP-010: R01
      SOP-011: R04
      SOP-013: R02
      SOP-016: R02
      SOP-017: R02
      SOP-018: R02
      SOP-019: R03
      SOP-020: R02
