---
version: 20
users:
  AliakseiT:
    full_name: Aliaksei Tsitovich
    job_title: Management Representative
  InaTsitovich:
    full_name: Ina Tsitovich
    job_title: Quality Assurance Lead
  SorenWesThorup:
    full_name: Søren Thorup
    job_title: Quality Assurance Lead

roles:
  qa_lead:
    users:
      - InaTsitovich
      - SorenWesThorup
    required_documents:
      - QM-001
      - SOP-001
      - SOP-002
      - SOP-003
      - SOP-005
      - SOP-006
      - SOP-007
      - SOP-008
      - SOP-009
      - SOP-010
      - SOP-011
      - SOP-012
      - SOP-013
      - SOP-014
      - SOP-015
      - SOP-016
      - SOP-017
      - SOP-018
      - SOP-019
      - SOP-020
    awareness_documents:
      - SOP-004
    required_revisions:
      QM-001: R02
      SOP-001: R13
      SOP-002: R04
      SOP-003: R05
      SOP-005: R16
      SOP-006: R03
      SOP-007: R06
      SOP-008: R07
      SOP-009: R07
      SOP-010: R03
      SOP-011: R09
      SOP-012: R04
      SOP-013: R04
      SOP-014: R04
      SOP-015: R04
      SOP-016: R04
      SOP-017: R04
      SOP-018: R07
      SOP-019: R10
      SOP-020: R09

  engineer:
    users:
      - AliakseiT
      - InaTsitovich
    required_documents:
      - QM-001
      - SOP-001
      - SOP-008
      - SOP-009
      - SOP-011
      - SOP-017
      - SOP-018
      - SOP-020
    awareness_documents:
      - SOP-002
      - SOP-006
      - SOP-015
      - SOP-019
    required_revisions:
      QM-001: R02
      SOP-001: R13
      SOP-008: R07
      SOP-009: R07
      SOP-011: R09
      SOP-017: R04
      SOP-018: R07
      SOP-020: R09

  engineering_lead:
    users:
      - AliakseiT
    required_documents:
      - QM-001
      - SOP-001
      - SOP-002
      - SOP-007
      - SOP-008
      - SOP-009
      - SOP-011
      - SOP-015
      - SOP-017
      - SOP-018
      - SOP-020
    awareness_documents:
      - SOP-006
      - SOP-019
    required_revisions:
      QM-001: R02
      SOP-001: R13
      SOP-002: R04
      SOP-007: R06
      SOP-008: R07
      SOP-009: R07
      SOP-011: R09
      SOP-015: R04
      SOP-017: R04
      SOP-018: R07
      SOP-020: R09

  technical_qms_maintainer:
    users:
      - AliakseiT
    required_documents:
      - QM-001
      - SOP-001
      - SOP-006
      - SOP-009
      - SOP-011
      - SOP-017
    awareness_documents:
      - SOP-002
      - SOP-007
      - SOP-018
      - SOP-020
    required_revisions:
      QM-001: R02
      SOP-001: R13
      SOP-006: R03
      SOP-009: R07
      SOP-011: R09
      SOP-017: R04

  regulatory_lead:
    users:
      - AliakseiT
    required_documents:
      - QM-001
      - SOP-001
      - SOP-002
      - SOP-003
      - SOP-004
      - SOP-005
      - SOP-006
      - SOP-007
      - SOP-008
      - SOP-009
      - SOP-010
      - SOP-011
      - SOP-012
      - SOP-013
      - SOP-014
      - SOP-015
      - SOP-016
      - SOP-017
      - SOP-018
      - SOP-019
      - SOP-020
    required_revisions:
      QM-001: R02
      SOP-001: R13
      SOP-002: R04
      SOP-003: R05
      SOP-004: R06
      SOP-005: R16
      SOP-006: R03
      SOP-007: R06
      SOP-008: R07
      SOP-009: R07
      SOP-010: R03
      SOP-011: R09
      SOP-012: R04
      SOP-013: R04
      SOP-014: R04
      SOP-015: R04
      SOP-016: R04
      SOP-017: R04
      SOP-018: R07
      SOP-019: R10
      SOP-020: R09

  usability_lead:
    users:
      - AliakseiT
    required_documents:
      - QM-001
      - SOP-001
      - SOP-008
      - SOP-011
      - SOP-012
      - SOP-014
      - SOP-018
      - SOP-019
    awareness_documents:
      - SOP-020
    required_revisions:
      QM-001: R02
      SOP-001: R13
      SOP-008: R07
      SOP-011: R09
      SOP-012: R04
      SOP-014: R04
      SOP-018: R07
      SOP-019: R10

  auditor:
    users: []
    required_documents:
      - QM-001
      - SOP-001
      - SOP-002
      - SOP-003
      - SOP-004
      - SOP-005
      - SOP-006
      - SOP-007
      - SOP-008
      - SOP-009
      - SOP-010
      - SOP-011
      - SOP-012
      - SOP-013
      - SOP-014
      - SOP-015
      - SOP-016
      - SOP-017
      - SOP-018
      - SOP-019
      - SOP-020
    required_revisions:
      QM-001: R02
      SOP-001: R13
      SOP-002: R04
      SOP-003: R05
      SOP-004: R06
      SOP-005: R16
      SOP-006: R03
      SOP-007: R06
      SOP-008: R07
      SOP-009: R07
      SOP-010: R03
      SOP-011: R09
      SOP-012: R04
      SOP-013: R04
      SOP-014: R04
      SOP-015: R04
      SOP-016: R04
      SOP-017: R04
      SOP-018: R07
      SOP-019: R10
      SOP-020: R09

  management_representative:
    users:
      - AliakseiT
    required_documents:
      - QM-001
      - SOP-001
      - SOP-002
      - SOP-003
      - SOP-004
      - SOP-005
      - SOP-006
      - SOP-007
      - SOP-008
      - SOP-009
      - SOP-010
      - SOP-011
      - SOP-012
      - SOP-013
      - SOP-014
      - SOP-015
      - SOP-016
      - SOP-017
      - SOP-018
      - SOP-019
      - SOP-020
    required_revisions:
      QM-001: R02
      SOP-001: R13
      SOP-002: R04
      SOP-003: R05
      SOP-004: R06
      SOP-005: R16
      SOP-006: R03
      SOP-007: R06
      SOP-008: R07
      SOP-009: R07
      SOP-010: R03
      SOP-011: R09
      SOP-012: R04
      SOP-013: R04
      SOP-014: R04
      SOP-015: R04
      SOP-016: R04
      SOP-017: R04
      SOP-018: R07
      SOP-019: R10
      SOP-020: R09
