#!/usr/bin/env python3
"""Generate an Electronic Signature Certificate PDF from signed attestation JSON."""

from __future__ import annotations

import argparse
import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from fpdf import FPDF
import yaml

DISCLAIMER_TEXT = (
    "This document is a human-readable manifestation of a cryptographically secure electronic "
    "signature. The definitive system of record is the associated JSON attestation and Sigstore "
    "cryptographic bundle hosted in the repository releases."
)


class ElectronicSignatureCertificatePDF(FPDF):
    def __init__(self, company_name: str, doc_title: str) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.company_name = company_name
        self.doc_title = doc_title
        self.alias_nb_pages()
        # 1-inch margins per specification.
        self.set_margins(25.4, 25.4, 25.4)
        self.set_auto_page_break(auto=True, margin=25.4)

    def header(self) -> None:
        self.set_font("Helvetica", "B", 11)
        content_width = self.w - self.l_margin - self.r_margin
        left_width = content_width * 0.5
        right_width = content_width - left_width

        self.cell(left_width, 6, self.company_name, border=0, align="L")
        self.cell(right_width, 6, self.doc_title, border=0, align="R")
        self.ln(8)

        y = self.get_y()
        self.set_draw_color(170, 170, 170)
        self.line(self.l_margin, y, self.w - self.r_margin, y)
        self.ln(5)

    def footer(self) -> None:
        # Disclaimer at bottom in italics.
        self.set_y(-19)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(70, 70, 70)
        self.multi_cell(0, 3, DISCLAIMER_TEXT)

        # Centered page numbering.
        self.set_y(-9)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(0, 0, 0)
        self.cell(0, 4, f"Page {self.page_no()} of {{nb}}", align="C")

        # Bottom-left generated marker.
        self.set_y(-5)
        self.set_font("Helvetica", "", 7)
        self.cell(0, 3, "Generated by qms-lite", align="L")


def _pick_value(attestation: dict[str, Any], keys: tuple[str, ...]) -> str:
    for key in keys:
        value = attestation.get(key)
        if value not in (None, ""):
            return str(value).strip()
    return ""


def _safe(value: str) -> str:
    return value if value else "n/a"

def _friendly_timestamp(ts: str) -> str:
    if not ts or ts == "n/a":
        return ts
    try:
        dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
        return dt.strftime("%d %b %Y %H:%M:%S UTC")
    except Exception:
        return ts


def _as_list(attestation: dict[str, Any]) -> list[dict[str, Any]]:
    if isinstance(attestation.get("signed_attestations"), list):
        return [x for x in attestation["signed_attestations"] if isinstance(x, dict)]

    # Fallback: single-signer legacy payload shapes.
    if any(attestation.get(k) for k in ("actor_login", "user_id", "signer_role", "signer_full_name")):
        return [
            {
                "user_id": attestation.get("actor_login") or attestation.get("user_id") or "",
                "signer_full_name": attestation.get("signer_full_name") or "",
                "signer_job_title": attestation.get("signer_job_title") or "",
                "signer_role": attestation.get("signer_role") or "",
                "meaning_of_signature": attestation.get("meaning_of_signature") or "",
                "timestamp": attestation.get("timestamp") or attestation.get("timestamp_utc") or "",
                "attestation_sha256": attestation.get("attestation_sha256") or attestation.get("attestation_id") or "",
            }
        ]

    return []


def _load_company_profile(profile_path: Path | None) -> dict[str, Any]:
    if not profile_path or not profile_path.exists():
        return {}
    try:
        data = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _resolve_preferred_display_role(
    company_profile: dict[str, Any],
    signer: dict[str, Any],
) -> str:
    prefs = company_profile.get("signature_preferences")
    if not isinstance(prefs, dict):
        return ""
    role_map = prefs.get("preferred_display_roles")
    if not isinstance(role_map, dict):
        return ""

    user_id = str(signer.get("user_id") or signer.get("actor_login") or "").strip().lower()
    full_name = str(signer.get("signer_full_name") or "").strip().lower()

    for raw_key, raw_value in role_map.items():
        key = str(raw_key or "").strip().lower()
        value = str(raw_value or "").strip()
        if not value:
            continue
        if key and key in {user_id, full_name}:
            return value
    return ""


def _normalized_signers(attestation: dict[str, Any], company_profile: dict[str, Any]) -> list[dict[str, str]]:
    top_meaning = _pick_value(attestation, ("meaning_of_signature",))
    normalized: list[dict[str, str]] = []
    for signer in _as_list(attestation):
        user_id = str(signer.get("user_id") or signer.get("actor_login") or "").strip()
        full_name = str(signer.get("signer_full_name") or "").strip()
        role = str(signer.get("signer_role") or "").strip() or "Unspecified role"
        title = str(signer.get("signer_job_title") or "").strip() or "n/a"
        preferred_role = _resolve_preferred_display_role(company_profile, signer)
        if preferred_role:
            role_title = preferred_role
        elif role.lower() == title.lower() or title == "n/a" or role == "Unspecified role":
            role_title = role if role != "Unspecified role" else (title if title != "n/a" else "Unspecified role")
        else:
            role_title = f"{role} / {title}"

        timestamp = _friendly_timestamp(str(signer.get("timestamp") or signer.get("timestamp_utc") or "").strip() or "n/a")
        sig_hash = str(signer.get("attestation_sha256") or signer.get("attestation_id") or "").strip()

        normalized.append(
            {
                "printed_user": f"{full_name or user_id or 'unknown'} (@{user_id or 'unknown'})",
                "role_title": role_title,
                "timestamp": timestamp,
                "sig_hash": sig_hash,
            }
        )
    return normalized


def _section_heading(pdf: FPDF, title: str) -> None:
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.multi_cell(0, 7, title)
    pdf.set_draw_color(190, 190, 190)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(2)


def _kv_lines(pdf: FPDF, rows: list[tuple[str, str]]) -> None:
    usable_width = pdf.w - pdf.l_margin - pdf.r_margin
    label_width = usable_width * 0.35
    value_width = usable_width * 0.65
    
    for label, value in rows:
        start_x = pdf.get_x()
        start_y = pdf.get_y()
        
        pdf.set_font("Helvetica", "B", 10)
        pdf.multi_cell(label_width, 6, f"{label}:", border=0)
        end_y_label = pdf.get_y()
        
        pdf.set_xy(start_x + label_width, start_y)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(value_width, 6, _safe(value), border=0, wrapmode="CHAR")
        end_y_value = pdf.get_y()
        
        # Advance Y to the maximum of label and value cells, adding some padding
        pdf.set_y(max(end_y_label, end_y_value) + 1)


def _wrap_text(pdf: FPDF, text: str, width: float) -> list[str]:
    value = _safe(text).replace("\t", " ")
    lines: list[str] = []
    for paragraph in value.splitlines() or [""]:
        words = paragraph.split()
        if not words:
            lines.append("")
            continue
        current = words[0]
        for word in words[1:]:
            candidate = f"{current} {word}"
            if pdf.get_string_width(candidate) <= width:
                current = candidate
            else:
                lines.append(current)
                current = word
        lines.append(current)
    return lines or [""]


def _draw_manifest_header(pdf: FPDF, widths: list[float], headers: list[str]) -> None:
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(235, 235, 235)
    for idx, header in enumerate(headers):
        pdf.cell(widths[idx], 8, header, border=1, align="C", fill=True)
    pdf.ln(8)


def _render_signature_manifest(pdf: FPDF, signers: list[dict[str, str]]) -> None:
    _section_heading(pdf, "Section 2: Signature Manifest")

    headers = [
        "Printed Name & User ID",
        "Role / Title",
        "Date & Time (UTC)",
    ]

    usable_width = pdf.w - pdf.l_margin - pdf.r_margin
    widths = [usable_width * 0.40, usable_width * 0.30, usable_width * 0.30]

    _draw_manifest_header(pdf, widths, headers)

    rows = signers or [
        {
            "printed_user": "n/a",
            "role_title": "n/a",
            "timestamp": "n/a",
            "sig_hash": "",
        }
    ]

    pdf.set_font("Helvetica", "", 9)
    line_h = 4.6

    for row in rows:
        values = [row["printed_user"], row["role_title"], row["timestamp"]]
        wrapped = [_wrap_text(pdf, values[i], widths[i] - 2) for i in range(3)]
        row_height = max(8.0, max(len(lines) for lines in wrapped) * line_h + 2)

        if pdf.get_y() + row_height > (pdf.h - pdf.b_margin):
            pdf.add_page()
            _section_heading(pdf, "Section 2: Signature Manifest (continued)")
            _draw_manifest_header(pdf, widths, headers)
            pdf.set_font("Helvetica", "", 9)

        start_x = pdf.get_x()
        start_y = pdf.get_y()
        cursor_x = start_x

        for col, lines in enumerate(wrapped):
            width = widths[col]
            pdf.rect(cursor_x, start_y, width, row_height)
            pdf.set_xy(cursor_x + 1, start_y + 1)
            pdf.multi_cell(width - 2, line_h, "\n".join(lines), border=0)
            cursor_x += width

        pdf.set_xy(start_x, start_y + row_height)


def _section_record_identification(pdf: FPDF, attestation: dict[str, Any], _record_id: str) -> None:
    source_repo = _pick_value(attestation, ("source_repository", "repository"))
    source_pr_title = _pick_value(attestation, ("source_pr_title", "pr_title"))
    source_pr = _pick_value(attestation, ("source_pull_request", "pr_number"))
    source_pr_url = _pick_value(attestation, ("source_pr_url", "pull_request_url"))
    source_target_commit = _pick_value(attestation, ("source_target_commit", "source_merge_commit", "target_commit"))

    record_title = f"{source_pr_title} (PR #{source_pr})".strip()
    if not source_pr_title and source_pr:
        record_title = f"PR #{source_pr}"

    _section_heading(pdf, "Section 1: Record Identification")
    _kv_lines(
        pdf,
        [
            ("Source Repository", source_repo),
            ("Record Title / PR", record_title),
            ("Record URL", source_pr_url),
            ("Target Git Commit (SHA)", source_target_commit),
        ],
    )


def _section_crypto_evidence(pdf: FPDF, attestation: dict[str, Any], signers: list[dict[str, str]]) -> None:
    captured_at = _pick_value(attestation, ("captured_at_utc", "timestamp_utc"))
    target_hash = _pick_value(attestation, ("part11_target_hash", "target_hash", "commit_hash"))
    attestation_log = _pick_value(attestation, ("source_attestation_comment_url", "request_comment_url"))

    hashes: list[str] = []
    for signer in signers:
        h = signer.get("sig_hash", "").strip()
        if h and h not in hashes:
            hashes.append(h)
    if not hashes:
        fallback_hash = _pick_value(attestation, ("attestation_sha256", "attestation_id"))
        if fallback_hash:
            hashes.append(fallback_hash)

    hash_value = "\n".join(f"- {h}" for h in hashes) if hashes else "n/a"

    _section_heading(pdf, "Section 3: Cryptographic Evidence")
    _kv_lines(
        pdf,
        [
            ("Attestation Capture Time", captured_at),
            ("Combined Target Hash", target_hash),
            ("Individual Signature Hash(es)", hash_value),
            ("Attestation Log", attestation_log),
        ],
    )


def _derive_output_path(attestation: dict[str, Any], output_arg: str) -> Path:
    if output_arg.strip():
        return Path(output_arg.strip())

    pr = _pick_value(attestation, ("source_pull_request", "pr_number")) or "unknown"
    pr_clean = re.sub(r"[^A-Za-z0-9_-]", "", pr) or "unknown"
    return Path(f"Electronic_Signature_Certificate_PR{pr_clean}.pdf")


def build_pdf(
    attestation: dict[str, Any],
    output_path: Path,
    record_id: str,
    company_name: str,
    doc_title: str,
    company_profile: dict[str, Any],
) -> None:
    signers = _normalized_signers(attestation, company_profile)

    pdf = ElectronicSignatureCertificatePDF(company_name=company_name, doc_title=doc_title)
    pdf.add_page()

    _section_record_identification(pdf, attestation, record_id)
    _render_signature_manifest(pdf, signers)
    _section_crypto_evidence(pdf, attestation, signers)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Electronic Signature Certificate PDF from attestation JSON.")
    parser.add_argument("--attestation", required=True, help="Path to signed_attestation.json")
    parser.add_argument("--output", default="", help="Output PDF path")
    parser.add_argument("--record-id", default="", help="Record identifier")
    parser.add_argument("--company", default="", help="Company name shown in header (default: ACME GmbH)")
    parser.add_argument(
        "--company-profile",
        default="matrices/company_profile.yml",
        help="Path to company_profile.yml for company metadata and display preferences",
    )
    args = parser.parse_args()

    attestation_path = Path(args.attestation)
    attestation = json.loads(attestation_path.read_text(encoding="utf-8"))
    company_profile_path = Path(args.company_profile).expanduser()
    company_profile = _load_company_profile(company_profile_path)

    company_name = args.company.strip() or _pick_value(attestation, ("company_name", "company", "organization"))
    if not company_name:
        company_name = _pick_value(company_profile.get("company", {}), ("legal_name",))
    if not company_name:
        company_name = os.environ.get("QMS_COMPANY_NAME", "").strip() or "ACME GmbH"

    doc_title = _pick_value(attestation, ("meaning_of_signature",)) or "Electronic Signature Certificate"

    output_path = _derive_output_path(attestation, args.output)
    build_pdf(attestation, output_path, args.record_id.strip(), company_name, doc_title, company_profile)


if __name__ == "__main__":
    main()
