name = "signature-worker"
main = "src/index.ts"
compatibility_date = "2026-03-02"
workers_dev = true

[[kv_namespaces]]
binding = "PIN_KV"
id = "9f16e609e2394104a5fcc45ecc0ef5ef"
preview_id = "df603f54cf7247a1b2a0dcc37e7bdcd7"

[vars]
PUBLIC_BASE_URL = "https://sign.qms.dearauditor.ch"
DEFAULT_OAUTH_PROVIDER = "github"
ALLOWED_OAUTH_PROVIDERS = "github"
